package:
  name: 'nionui'
  version: '7.1.1'

source:
  git_rev: 7.1.1
  git_url: https://github.com/nion-software/nionui.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False
  entry_points:
    - nionui = nion.ui.command:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.9
    - nionutils >=4.11.0,<5.0.0
    - numpy >=1.21,<2.0
    - imageio >=2.19.0

test:
  imports:
    - nion.ui
    - nion.ui.test

about:
  home: https://github.com/nion-software/nionui
  license: Apache-2.0
  summary: Nion UI classes.
  description: "A library of useful UI objects."

extra:
  recipe-maintainers:
    cmeyer
